"""Initial migration with pincode fields

Revision ID: 917b8325cb52
Revises: 
Create Date: 2025-06-13 15:57:33.765808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917b8325cb52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add pincode column as nullable first
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=6), nullable=True))
    
    with op.batch_alter_table('hospital_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=6), nullable=True))
    
    # Update existing records with a default pincode
    op.execute("UPDATE donor_profile SET pincode = '000000'")
    op.execute("UPDATE hospital_profile SET pincode = '000000'")
    
    # Make pincode columns non-nullable
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.alter_column('pincode', nullable=False)
    
    with op.batch_alter_table('hospital_profile', schema=None) as batch_op:
        batch_op.alter_column('pincode', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_profile', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.drop_column('pincode')
    # ### end Alembic commands ###
